#
# Module manifest for module 'Az'
#
# Generated by: Microsoft Corporation
#
# Generated on: 5/20/2026
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '16.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd48d710e-85cb-46a1-990f-22dae76f6b5f'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with PowerShell and Windows PowerShell.
For more information about the Az module, please visit the following: https://learn.microsoft.com/powershell/azure/'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '5.4.2'; }, 
               @{ModuleName = 'Az.Advisor'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.Aks'; RequiredVersion = '7.1.2'; }, 
               @{ModuleName = 'Az.AnalysisServices'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.ApiManagement'; RequiredVersion = '4.1.0'; }, 
               @{ModuleName = 'Az.App'; RequiredVersion = '2.0.1'; }, 
               @{ModuleName = 'Az.AppConfiguration'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.ApplicationInsights'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.ArcResourceBridge'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.ArizeAI'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.Attestation'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.Automanage'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.Automation'; RequiredVersion = '1.11.2'; }, 
               @{ModuleName = 'Az.Batch'; RequiredVersion = '4.0.1'; }, 
               @{ModuleName = 'Az.Billing'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.Cdn'; RequiredVersion = '6.0.2'; }, 
               @{ModuleName = 'Az.CloudService'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.CognitiveServices'; RequiredVersion = '1.16.0'; }, 
               @{ModuleName = 'Az.Compute'; RequiredVersion = '11.6.0'; }, 
               @{ModuleName = 'Az.ConfidentialLedger'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.ConnectedMachine'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.ContainerInstance'; RequiredVersion = '5.0.0'; }, 
               @{ModuleName = 'Az.ContainerRegistry'; RequiredVersion = '5.0.1'; }, 
               @{ModuleName = 'Az.CosmosDB'; RequiredVersion = '1.20.0'; }, 
               @{ModuleName = 'Az.DataBoxEdge'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.Databricks'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.DataFactory'; RequiredVersion = '1.19.7'; }, 
               @{ModuleName = 'Az.DataLakeAnalytics'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.DataLakeStore'; RequiredVersion = '1.5.2'; }, 
               @{ModuleName = 'Az.DataMigration'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.DataProtection'; RequiredVersion = '2.10.1'; }, 
               @{ModuleName = 'Az.DataShare'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.DataTransfer'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.DesktopVirtualization'; RequiredVersion = '6.0.0'; }, 
               @{ModuleName = 'Az.DevCenter'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.DeviceRegistry'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.DevTestLabs'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Dns'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.DnsResolver'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.ElasticSan'; RequiredVersion = '1.7.0'; }, 
               @{ModuleName = 'Az.EventGrid'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.EventHub'; RequiredVersion = '5.4.0'; }, 
               @{ModuleName = 'Az.Fabric'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.FileShare'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.FirmwareAnalysis'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.FrontDoor'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.Functions'; RequiredVersion = '5.0.0'; }, 
               @{ModuleName = 'Az.HDInsight'; RequiredVersion = '6.4.0'; }, 
               @{ModuleName = 'Az.HealthcareApis'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.HealthDataAIServices'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.IotHub'; RequiredVersion = '2.8.1'; }, 
               @{ModuleName = 'Az.KeyVault'; RequiredVersion = '6.4.4'; }, 
               @{ModuleName = 'Az.Kusto'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.LambdaTest'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.LoadTesting'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.LogicApp'; RequiredVersion = '1.6.0'; }, 
               @{ModuleName = 'Az.MachineLearning'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.MachineLearningServices'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.Maintenance'; RequiredVersion = '1.5.1'; }, 
               @{ModuleName = 'Az.ManagedServiceIdentity'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.ManagedServices'; RequiredVersion = '4.0.0'; }, 
               @{ModuleName = 'Az.MarketplaceOrdering'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.Migrate'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.Monitor'; RequiredVersion = '8.0.0'; }, 
               @{ModuleName = 'Az.MySql'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.NetAppFiles'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.Network'; RequiredVersion = '8.0.0'; }, 
               @{ModuleName = 'Az.NetworkCloud'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.Nginx'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.NotificationHubs'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.OperationalInsights'; RequiredVersion = '3.3.0'; }, 
               @{ModuleName = 'Az.Oracle'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.PolicyInsights'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.PostgreSql'; RequiredVersion = '1.4.1'; }, 
               @{ModuleName = 'Az.PowerBIEmbedded'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.PrivateDns'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.RecoveryServices'; RequiredVersion = '7.11.3'; }, 
               @{ModuleName = 'Az.RedisCache'; RequiredVersion = '1.11.0'; }, 
               @{ModuleName = 'Az.RedisEnterpriseCache'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.Relay'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.ResourceGraph'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.ResourceMover'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.Resources'; RequiredVersion = '10.0.0'; }, 
               @{ModuleName = 'Az.Security'; RequiredVersion = '1.8.0'; }, 
               @{ModuleName = 'Az.SecurityInsights'; RequiredVersion = '3.2.2'; }, 
               @{ModuleName = 'Az.ServiceBus'; RequiredVersion = '4.1.1'; }, 
               @{ModuleName = 'Az.ServiceFabric'; RequiredVersion = '5.2.0'; }, 
               @{ModuleName = 'Az.SignalR'; RequiredVersion = '2.3.3'; }, 
               @{ModuleName = 'Az.Sql'; RequiredVersion = '7.0.0'; }, 
               @{ModuleName = 'Az.SqlVirtualMachine'; RequiredVersion = '2.4.1'; }, 
               @{ModuleName = 'Az.StackHCI'; RequiredVersion = '2.7.1'; }, 
               @{ModuleName = 'Az.StackHCIVM'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.Storage'; RequiredVersion = '9.7.0'; }, 
               @{ModuleName = 'Az.StorageAction'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.StorageDiscovery'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.StorageMover'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.StorageSync'; RequiredVersion = '2.5.2'; }, 
               @{ModuleName = 'Az.StreamAnalytics'; RequiredVersion = '3.0.0'; }, 
               @{ModuleName = 'Az.Support'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Synapse'; RequiredVersion = '3.2.4'; }, 
               @{ModuleName = 'Az.TrafficManager'; RequiredVersion = '1.3.0'; }, 
               @{ModuleName = 'Az.Websites'; RequiredVersion = '3.4.3'; }, 
               @{ModuleName = 'Az.Workloads'; RequiredVersion = '2.0.0'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ARM','ResourceManager','Linux','AzureAutomationNotSupported'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '16.0.0 - June 2026
Az.Accounts
* Upgraded ''Azure.Identity'' dependency to 1.17.2.

Az.CloudService
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.Compute
* Added ''-InstantAccess'' parameter to ''New-AzRestorePointCollection'' cmdlet to enable instant access snapshots for restore points on Premium SSD v2 and Ultra disks
* Added ''-InstantAccess'' parameter to ''Update-AzRestorePointCollection'' cmdlet to enable or disable instant access on an existing restore point collection
* Added ''-InstantAccessDurationInMinutes'' parameter to ''New-AzRestorePoint'' cmdlet to specify the duration (1-300 minutes) for which the instant access snapshot is retained

Az.ContainerInstance
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.Databricks
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.DataProtection
* Changed ''Edit-AzDataProtectionPolicyRetentionRuleClientObject'' to require ''-Name Default_OperationalStore'' for OperationalStore lifecycles
* Added ''-RenameTo'' to ''Initialize-AzDataProtectionRestoreRequest'' for alternate-location restore
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).
* Added Azure Cosmos DB protection support (configure, backup, restore)

Az.DesktopVirtualization
* Upgraded API version to 2025-10-10
* Added MultiplePersistent enum value to HostPool property loadBalancerType.
* Fixed an issue where ''New-AzWvdRegistrationInfo'' failed when public network access was disabled on the host pool.
* Fixed an issue where ''Remove-AzWvdRegistrationInfo'' failed when public network access was disabled on the host pool.

Az.DnsResolver
* Upgraded API version to 2025-10-01-preview
* Added ''Invoke-AzDnsResolverBulkDnsResolverDomainList'' for bulk domain upload
* Upgraded code generator. See [details](https://go.microsoft.com/fwlink/?linkid=2340249).
* Removed ''-ActionBlockResponseCode'' from ''New/Update-AzDnsResolverPolicyDnsSecurityRule''
* Changed ''-DnsResolverDomainList'' to optional on ''New-AzDnsResolverPolicyDnsSecurityRule'' (supports ''ManagedDomainList'')
* Changed ''-Domain'' to optional on ''New-AzDnsResolverDomainList'' (supports bulk upload)

Az.FileShare
* General availability for module Az.FileShare

Az.FrontDoor
* Upgraded API version to 2025-11-01
* Hid non-public cmdlets: ''NetworkExperimentProfile'', ''Experiment'', ''PreconfiguredEndpoint'', ''ReportLatencyScorecard'', ''ReportTimesery''
* Fixed ''New/Remove-AzFrontDoorWafPolicy'' ''UriFormatException'' by rewriting LRO ''final-state-via''

Az.Functions
* Migrated Az.Functions from AutoRest PowerShell v3 to v4. See breaking changes [here](https://go.microsoft.com/fwlink/?linkid=2340249).
    - Replaced ''-IdentityType''/''-IdentityID'' with ''-EnableSystemAssignedIdentity''/''-UserAssignedIdentity''
    - Enabled combining SystemAssigned and UserAssigned identities
* Fixed error messages to reference ''-EnableSystemAssignedIdentity'' instead of removed ''-IdentityType''
* Added SKU validation in ''Update-AzFunctionApp'' for Flex Consumption and Container App plans
* Fixed cloud portability using dynamic ''StorageEndpointSuffix'' [#29034]
* Fixed ''Update-AzFunctionApp'' identity fallback to preserve combined identity type

Az.KeyVault
* Fixed ''New-AzKeyVault'' ''RequestDisallowedByPolicy'' error by setting ''enableSoftDelete'' in request body
* [Breaking Change] Certificate-backed keys and secrets are no longer returned by ''Get-AzKeyVaultKey'' and ''Get-AzKeyVaultSecret''. Use ''Get-AzKeyVaultCertificate'' to manage certificates and their associated keys and secrets. [#26217]

Az.Kusto
* Improved user experience and consistency. This may introduce breaking changes. Please refer to [here](https://go.microsoft.com/fwlink/?linkid=2340249).
* Preannounced breaking changes. Please refer to https://go.microsoft.com/fwlink/?linkid=2333229

Az.LoadTesting
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.MachineLearningServices
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.ManagedServices
* Upgraded code generator. See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.Migrate
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.Monitor
* Updated MonitorWorkspace module to API 2025-10-03 with CRUD cmdlets for issues, alerts, resources, investigation, visualization, metrics containers, and ''Set-AzMonitorWorkspace''
* Upgraded Pipelines API to GA 2026-04-01: added ''-DistributionMaxInstancesPerHost'', ''-ExecutionPlacementConstraint'', ''-TlsConfiguration''; removed ''-NetworkingConfiguration'', UDP receiver, ''TcpUrl'', ''JsonArrayMapperKey'', ''SourceFieldName'', ''SyslogProtocol'', ''DestinationField*''; expanded parameter sets

Az.MySql
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.Network
* Changed ''UserAssignedIdentityId'' type from string to string[] in Azure Firewall Policy

Az.PolicyInsights
* Changed output types: ''PSAttestation'' → ''Attestation'', ''PSPolicyMetadata'' → ''PolicyMetadata'', ''PSRemediation'' → ''Remediation''; flattened ''SystemData'' and added ''ResourceGroupName''
* Renamed ''ResourceTags''/''ManagementGroupIds'' to singular forms in ''Get-AzPolicyEvent''/''Get-AzPolicyState''
* Flattened ''Get-AzPolicyStateSummary'' and remediation output properties
* Changed ''Start-AzPolicyRemediation'' to wait for terminal state by default (added ''-NoWait'')
* Changed ''Stop-AzPolicyRemediation'' output from ''bool'' to ''Remediation'' (added ''-NoWait'')

Az.RecoveryServices
* Added soft delete support for Azure File share backup items (''Undo-AzRecoveryServicesBackupItemDeletion'' and ''Get-AzRecoveryServicesBackupItem -DeleteState SoftDeleted'')

Az.RedisEnterpriseCache
* Upgraded code generator. See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.ResourceMover
* Improved usability and consistency (possible breaking changes). See [here](https://go.microsoft.com/fwlink/?linkid=2340249).

Az.Resources
* Updated deployment stack cmdlets to use the ''2025-07-01'' deployment stacks service version.
* Added ''-ResourcesWithoutDeleteSupport'' to deployment stack ''New-'', ''Set-'', ''Test-'', and ''Remove-'' cmdlets at subscription, resource group, and management group scopes. This parameter controls whether resources that do not support deletion cause the operation to fail or are detached from the stack. Possible values: ''Fail'' (default) and ''Detach''.
* Added ''-ValidationLevel'' to deployment stack ''New-'', ''Set-'', and ''Test-'' cmdlets at subscription, resource group, and management group scopes. This parameter controls how deployment stack validation is performed. Possible values: ''Provider'' (default), ''Template'', and ''ProviderNoRbac'' (provider validation without Role-Based Access Control checks).
* Deployment stack command output now includes the resource deletion support behavior and validation level for the stack.
* Fixed ''Set-AzRoleAssignment'' unable to delete conditions from a role assignment
* Updated Policy.Autorest to 2025-03-01: added ''-Expand'' to ''Get-AzPolicyAssignment''/''Get-AzPolicySetDefinition''; removed ''-BackwardCompatible''; added Enroll ''-EnforcementMode'' and ExternalEvaluationEnforcementSettings; extended ''-Version'' support

Az.ServiceFabric
* Added ''Enable-AzServiceFabricManagedClusterMaintenanceWindow'' and ''Get-AzServiceFabricManagedClusterMaintenanceWindowStatus'' cmdlets

Az.Sql
* Removed the ''EnableSoftDelete'' parameter from ''New-AzSqlServer'' and ''Set-AzSqlServer'' cmdlets. Use the ''SoftDeleteRetentionDays'' parameter instead: setting ''SoftDeleteRetentionDays'' to 1-7 enables soft-delete, and setting it to 0 disables soft-delete.
* Reverted ''the support for UAMI authentication in Data Sync cmdlets''

Az.Storage
* Added Smart access tier and AllowedCopyScope ''All'' support in ''New/Set-AzStorageAccount''
* Added static website configuration in ''Update-AzStorageBlobServiceProperty''
* Added tags replication in ''Set-AzStorageObjectReplicationPolicy''

Az.StorageAction
* Internal code generation updated. No user-facing changes in this release.

Az.StorageMover
* Upgraded API version to 2025-12-01 (Connection resources, S3 HMAC endpoint, data integrity validation, schedule info, job run warnings)
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

